create table
  public.cart_items (
    id integer generated by default as identity,
    item_sku text not null,
    cart_id integer null,
    quantity integer not null default 0,
    constraint cart_tems_pkey primary key (id),
    constraint cart_tems_id_key unique (id),
    constraint public_cart_tems_cart_fkey foreign key (cart_id) references carts (id),
    constraint public_cart_tems_item_fkey foreign key (item_sku) references potion_types (sku)
  ) tablespace pg_default;

  create table
  public.carts (
    id integer generated by default as identity,
    customer_name text not null,
    character_class text not null,
    level integer not null,
    constraint carts_pkey primary key (id),
    constraint carts_id_key unique (id)
  ) tablespace pg_default;


  create table
  public.global_inventory (
    green_ml integer not null,
    red_ml integer not null default 0,
    blue_ml integer not null default 0,
    ml_capacity integer not null default 10000,
    dark_ml integer not null default 0,
    ml_threshold integer not null default 5000,
    potion_capacity integer not null default 50,
    potion_count integer not null default 0,
    pk integer not null default 1,
    gold integer not null default 100,
    constraint global_inventory_pkey primary key (pk)
  ) tablespace pg_default;

  create table
  public.potion_types (
    sku text not null,
    red_ml integer not null default 0,
    green_ml integer not null default 0,
    blue_ml integer not null default 0,
    dark_ml integer not null default 0,
    quantity integer not null default 0,
    price integer null default 25,
    constraint potion_types_pkey primary key (sku)
  ) tablespace pg_default;

  